server:
  error:
    include-binding-errors: always
    include-message: always
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/taskie?serverTimezone=UTC
    username: developer
    password: 'developer'
    driver-class-name: com.mysql.cj.jdbc.Driver