server:
  error:
    include-binding-errors: always
    include-message: always
  port: ${PORT:8080}
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://us-cdbr-east-05.cleardb.net/heroku_f59a365f89a617f?reconnect=true
    username: b4786f8f8e2ec1
    password: ea30a17e
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  securityKey: 'securesecuresecurehbsfljjkdwnlDWscjkcfbkt8322yroyo823ye29ogdiqeo2y282u7g2d28u2fwiut821yw'
  tokenPrefix: 'Bearer'
  expirationAfterDays: 14